# Generated by Django 4.1.3 on 2022-12-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220209_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pusblisher',
            name='user',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryArabic',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryEnglish',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryfranch',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Public',
        ),
        migrations.DeleteModel(
            name='Pusblisher',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
