# Generated by Django 4.1.3 on 2022-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_order_client_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
