# Generated by Django 4.1.3 on 2022-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
