# Generated by Django 4.1.3 on 2022-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_payment_cheque_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cheque_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
