# Generated by Django 4.1.3 on 2022-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_product_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
