# Generated by Django 4.1.3 on 2022-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
