# Generated by Django 4.1.3 on 2022-12-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_product_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
    ]
